### ISSUE TITLE
is:issue is:open 如何实现回到顶部得功能？我修改了content.jsx文件实现了，请问有更优得方案吗？

### ISSUE THREAD

**Issue by QiuPang** [cmux/koot#197]

**Comment by Diablohu** [comment]
这种页面功能目前没有统一的方案，如有需求需要自行实现

下面是一段我这边项目用到的操作滚动条的代码，可供参考

```typescript

/**
 * 滚动至指定 Y 坐标或目标元素的位置
 */
const scrollTo = (YorElement: number | HTMLElement, offset = 0): void => {
    let y = offset;
    if (typeof YorElement === 'number') {
        y += YorElement;
    } else if (YorElement instanceof Element) {
        const rect = YorElement.getBoundingClientRect();
        y += rect.top + window.pageYOffset;
    }
    doScroll(y);
};

export default scrollTo;

// =======================

const doScroll = (y: number): void => {
    if (typeof window.scroll === 'function') {
        try {
            window.scroll({
                top: y,
                left: 0,
                behavior: 'smooth'
            });
        } catch (e) {
            doScrollFallback(y);
        }
    } else {
        doScrollFallback(y);
    }
};

const doScrollFallback = (y: number): void => {
    window.scrollTo(0, y);
};

```

`window.scroll` 是一个新的浏览器函数，可以控制滚动行为，这里用到了 `behavior: 'smooth'`，原生实现平滑滚动

**Comment by QiuPang** [comment]
收到，非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Diablohu"<notifications@github.com&gt;; 
发送时间: 2019年12月16日(星期一) 下午4:51
收件人: "cmux/koot"<koot@noreply.github.com&gt;; 
抄送: "邱源"<1037428670@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cmux/koot] is:issue is:open 如何实现回到顶部得功能？我修改了content.jsx文件实现了，请问有更优得方案吗？ (#197)




这种页面功能目前没有统一的方案，如有需求需要自行实现
 
下面是一段我这边项目用到的操作滚动条的代码，可供参考
 /**  * 滚动至指定 Y 坐标或目标元素的位置  */ const scrollTo = (YorElement: number | HTMLElement, offset = 0): void =&gt; {     let y = offset;     if (typeof YorElement === 'number') {         y += YorElement;     } else if (YorElement instanceof Element) {         const rect = YorElement.getBoundingClientRect();         y += rect.top + window.pageYOffset;     }     doScroll(y); }; export default scrollTo; // ======================= const doScroll = (y: number): void =&gt; {     if (typeof window.scroll === 'function') {         try {             window.scroll({                 top: y,                 left: 0,                 behavior: 'smooth'             });         } catch (e) {             doScrollFallback(y);         }     } else {         doScrollFallback(y);     } }; const doScrollFallback = (y: number): void =&gt; {     window.scrollTo(0, y); }; 
 
window.scroll 是一个新的浏览器函数，可以控制滚动行为，这里用到了 behavior: 'smooth'，原生实现平滑滚动
