### ISSUE TITLE
支持serverless

### ISSUE THREAD

**Issue by daqi** [cmux/koot#217]
目标：
实现ssr项目支持serverless部署

需求：
- koa实例化从异步方式改成同步方式
- 导出koa实例，不需要监听（listen）端口
- 精简依赖，只保留运行所需依赖

**Comment by Diablohu** [comment]
serverless 脚本比 Web 服务器的区别

- 不会自动检查端口是否被占用
- 不会自动侦听端口
- 默认输出 koa app 实例
- `serverBefore` 和 `serverAfter` 生命周期方法必须为同步函数

**Comment by Diablohu** [comment]
目前已可用

demo: http://service-kunit5z5-1252144562.bj.apigw.tencentcs.com/

其他问题有待进一步观察

**Comment by daqi** [comment]
服务端打包不会编译依赖进去，导致node_module体积过大，无法发布

**Comment by Diablohu** [comment]
@daqi fix in https://github.com/cmux/koot/releases/tag/v0.13.3
