### ISSUE TITLE
webpack无限打包

### ISSUE THREAD

**Issue by chenqinyang1994** [cmux/koot#59]
webpack无限打包问题可能是因为多次保存，上一次保存webpack打包还没有结束，下一次的保存已经来了，可能引发了无限打包问题。

**Comment by Diablohu** [comment]
已修复。修复方案：

- `devtool` 默认值修改为 `cheap-module-eval-source-map` (08311288dbfaa8a6bc317ce8d2768ecc216c6c60)
- 添加 `thread-loader` (37adbfaf4faf02bcb4581e5e55f3369e7318984c)
- 添加 `cache-loader` (6cfe7c7a752bae827696967fe58bab582ff0891e)
- 取消配置项 `devHmr` 的默认值 (b2caeb43527959cc708c74316c3dafe698b36cf3)
