### ISSUE TITLE
CSS的类名为.component的问题

### ISSUE THREAD

**Issue by chenqinyang1994** [cmux/koot#68]
css的类名是.component的时候，在本地运行没有问题，打包到测试环境或者线上就会出现该类名没有对应的样式的Bug

**Comment by Diablohu** [comment]
处理方案
- 类似 `.component .component` 这样使用空格 (` `) 选择器时，现在选择器之后的 `.component` 字段会被保留，不会进行 hash
- 使用其他选择器的情况依旧会进行 hash
